development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://pzjgjpgunvwjzs:3cTE55YNJLYzP_S5KDHDGA-2aL@ec2-54-243-201-116.compute-1.amazonaws.com:5432/d3uc45v4lhrol8
